name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/meiraba_school/node/Smart-Delivery-Bin
            
            # Pull latest changes
            git pull origin main
            
            # Install any new dependencies
            npm install
            
            # Restart PM2 process
            pm2 restart delivery-box

      - name: Notify on Failure
        if: failure()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "@everyone DEPLOYMENT FAILED! "
          embed-description: "`api.meiraba.me` Check the GitHub Actions log for details: \n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          embed-title: "Deployment FAILED!"
          embed-color: 15158332 # Red

      - name: Notify on Success
        if: success()
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "@everyone Deployment process successful!."
          embed-description: "`api.meiraba.me` was updated with the latest push."
          embed-title: "✅ Deployment Successful!"
          embed-color: 3066993
